version: "3.9"
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "400MB"
    healthcheck:
      test: [ "CMD", "pg_isready", "--username", "admin" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s

    

  app1: &api
    image: otonielsilva/rinhabackend:latest
    hostname: app1
    depends_on:
      - db

    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://127.0.0.1:5432/rinha
      - QUARKUS_DATASOURCE_JDBC_MIN_SIZE=15
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=25
      - QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=15
      - QUARKUS_HTTP_IDLE_TIMEOUT=45
      - QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=60
      - QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=15S
      - QUARKUS_HTTP_PORT=8081
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "75MB"
    network_mode: host      

  app2:
    <<: *api
    hostname: app2
    ports:
      - "8082:8080"
    environment: 
      - QUARKUS_HTTP_PORT=8081  
    network_mode: host


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"
    depends_on:
      - app1
      - app2
    network_mode: host  